### ISSUE TITLE
Question about configuration method

### ISSUE THREAD

**Issue by EuCaue** [nyarthan/telescope-code-actions.nvim#5]
```lua
require('telescope').load_extension('telescope-code-actions')
```

In my telescope, this doesn't work, but 
```lua
require("telescope").load_extension("code_actions")
```
Works flawless, I don't know with it's a bug or not, just asking with it's supposed to work on this way.

**Comment by nyarthan** [comment]
I've also had some trouble with loading it via `load_extension`. I would recommend just putting in as an extension in your setup like this
```lua
require('telescope').setup({
  extensions = {
    ['telescope-code-actions'] = {},
  },
})
```

That beeing said, I should definitley look into it and update the documentation accordingly.
